Path: ''
Output:
  Folder: output files
Files:
  - Styles/Scroll Deck Style.yaml
  - Databases/DND5e Equipment.yaml
  - Cards/Spells.yaml
  - Cards/Weapons.yaml
  - Cards/Magical Items.yaml
  - Cards/Packs.yaml
  - Cards/Coinage.yaml
  - Cards/Conditions.yaml
  - Cards/Skills.yaml
  - Cards/Actions.yaml
  - Cards/Armor.yaml
  - Cards/Features.yaml
  - Cards/Creatures.yaml
  - Cards/Rules.yaml
  - Cards/Items.yaml
