Path: cards
Files:
  - Scroll Deck Style.yaml
  - DND5eApi Equipment.yaml
  - Spells.yaml
  - Weapons.yaml
  - Magical Items.yaml
  - Packs.yaml
  - Coinage.yaml
  - Conditions.yaml
  - Skills.yaml
  - Actions.yaml
  - Armor.yaml
  - Capabilities.yaml
  - Creatures.yaml
  - Rules.yaml
  - Items.yaml